apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "testing-webhooks.fullname" . }}:manager-rolebinding
  labels:
    {{- include "testing-webhooks.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "testing-webhooks.fullname" . }}:manager
subjects:
- kind: ServiceAccount
  name: {{ include "testing-webhooks.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
